harness:
  subdomain: workspaces
  secured: true
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    volume:
      name: salk-files
      mountpath: /usr/src/app/persistent
      auto: true
      size: 5Gi
    resources:
      requests:
        memory: "1536Mi"
        cpu: "250m"
      limits:
        memory: "1536Mi"
        cpu: "250m"
  database:
    auto: true
    type: postgres
  livenessProbe:
    path: /k8s/live
  readinessProbe:
    path: /k8s/ready
  dependencies:
    build:
    - cloudharness-base-debian
    - workspaces-base
    hard:
    - accounts
    - events
    - argo
  uri_role_mapping:
    - uri: /api/*
      roles:
        - workspaces:workspaces-user
        - workspaces:workspaces-administrator
      require-any-role: true
    - uri: /admin/*
      roles:
        - workspaces:workspaces-administrator
