harness:
  subdomain: workspaces
  secured: true
  service:
    port: 8000
    auto: true
  deployment:
    auto: true
    port: 8000
  livenessProbe:
    path: /api/ui
  readinessProbe:
    path: /api/ui
  dependencies:
    build:
    - cloudharness-base
    hard:
    - accounts
    - kafka
    - events
