harness:
  subdomain: workspaces
  secured: true
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    volume:
      name: salk-files
      mountpath: /usr/src/app/persistent
      auto: true
      size: 5Gi
    resources:
      requests:
        memory: "1024Mi" # for cordmap density map we need at least 800Mi memory
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  database:
    auto: true
    type: postgres
  livenessProbe:
    path: /k8s/live
  readinessProbe:
    path: /k8s/ready
  dependencies:
    build:
    - cloudharness-base-debian
    hard:
    - accounts
    - events
  uri_role_mapping:
    - uri: /api/*
      roles:
        - workspaces:workspaces-user
        - workspaces:workspaces-administrator
      require-any-role: true
    - uri: /admin/*
      roles:
        - workspaces:workspaces-administrator
