harness:
  subdomain: workspaces
  secured: true
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    volume:
      name: salk-files
      mountpath: /usr/src/app/persistent
      size: 5Gi
  database:
    auto: true
    type: postgres
  livenessProbe:
    path: /k8s/live
  readinessProbe:
    path: /k8s/ready
  dependencies:
    build:
    - cloudharness-base
    hard:
    - accounts
    - events
  use_services:
    - name: common
  uri_role_mapping:
    - uri: /api/*
      roles:
        - workspaces:workspaces-user
        - workspaces:workspaces-administrator
      require-any-role: true
    - uri: /admin/*
      roles:
        - workspaces:workspaces-administrator
