harness:
  subdomain: www
  secured: true
  deployment:
    auto: true
    port: 80
  service:
    auto: true
    port: 80
  resources:
    - name: "keycloak"
      src: "keycloak.json"
      dst: "/usr/share/nginx/html/keycloak.json"
  sentry: true
  use_services:
    - name: workspaces
    - name: common
  dependencies:
    soft:
      - accounts
      - common
      - volumemanager
      - workspaces
      # - workflows
      # - jupyterhub
      # - jupyterlab
      # - hub
  uri_role_mapping:
    - uri: /*
      roles:
        - default-roles-salk
