harness:
  subdomain: www
  secured: true
  deployment:
    auto: true
    port: 80
    volume:
      name: salk-files
      mountpath: /usr/share/nginx/html/persistent
      auto: false
      readonly: true
      size: 5Gi
  service:
    auto: true
    port: 80
  resources:
    - name: "keycloak"
      src: "keycloak.json"
      dst: "/usr/share/nginx/html/keycloak.json"
  sentry: false
  use_services:
    - name: workspaces
  dependencies:
    soft:
      - accounts
      - workspaces
  uri_role_mapping:
    - uri: /*
      roles:
        - default-roles-salk
    - uri: /avatars/*
      white-listed: true
