apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.apps.workspaces.harness.deployment.name }}-migrate"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.apps.workspaces.harness.deployment.name| quote }}
    usesvolume: {{ .Values.apps.workspaces.harness.deployment.volume.name }}
  {{ include "deploy_utils.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.apps.workspaces.harness.deployment.name| quote }}
        usesvolume: {{ .Values.apps.workspaces.harness.deployment.volume.name }}
      {{ include "deploy_utils.labels" . | indent 8 }}
    spec:
      containers:
      - name: "{{ .Values.apps.workspaces.harness.deployment.name }}-migrate"
        image: "{{- .Values.apps.workspaces.harness.deployment.image }}"
        command: ["python",  "manage.py", "migrate"]
        env:
        - name: CH_CURRENT_APP_NAME
          value: {{ .Values.apps.workspaces.harness.name | quote }}
          {{- include "deploy_utils.env" . | nindent 8 }}
          {{- include "deploy_utils.privenv" . | nindent 8 }}
          {{- if .Values.apps.workspaces.harness.env }}
            {{- .Values.apps.workspaces.harness.env | toYaml | nindent 8 }}
          {{- end }}
        volumeMounts:
          - name: cloudharness-allvalues
            mountPath: /opt/cloudharness/resources
            readOnly: true
          - name: cloudharness-kc-accounts
            mountPath: /opt/cloudharness/resources/auth
            readOnly: true
          {{- if .Values.apps.workspaces.harness.deployment.volume }}
          - name: {{ .Values.apps.workspaces.harness.deployment.volume.name }}
            mountPath: {{ .Values.apps.workspaces.harness.deployment.volume.mountpath }}
            readOnly: {{ .Values.apps.workspaces.harness.deployment.volume.readonly | default false }}
          {{- end }}
      volumes:
        - name: cloudharness-allvalues
          configMap:
            name: cloudharness-allvalues
        - name: cloudharness-kc-accounts
          secret:
            secretName: accounts
        {{- if .Values.apps.workspaces.harness.deployment.volume }}
        - name: {{ .Values.apps.workspaces.harness.deployment.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.apps.workspaces.harness.deployment.volume.name }}
        {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 20
