/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentUser
 */
export interface ExperimentUser {
    /**
     * 
     * @type {number}
     * @memberof ExperimentUser
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExperimentUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentUser
     */
    email?: string;
}

export function ExperimentUserFromJSON(json: any): ExperimentUser {
    return ExperimentUserFromJSONTyped(json, false);
}

export function ExperimentUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function ExperimentUserToJSON(value?: ExperimentUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'email': value.email,
    };
}


