/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentTeams
 */
export interface ExperimentTeams {
    /**
     * 
     * @type {number}
     * @memberof ExperimentTeams
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExperimentTeams
     */
    name: string;
}

export function ExperimentTeamsFromJSON(json: any): ExperimentTeams {
    return ExperimentTeamsFromJSONTyped(json, false);
}

export function ExperimentTeamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentTeams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function ExperimentTeamsToJSON(value?: ExperimentTeams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


