/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExperimentUser,
    ExperimentUserFromJSON,
    ExperimentUserFromJSONTyped,
    ExperimentUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface ExperimentCollaborators
 */
export interface ExperimentCollaborators {
    /**
     * 
     * @type {ExperimentUser}
     * @memberof ExperimentCollaborators
     */
    user?: ExperimentUser;
    /**
     * 
     * @type {string}
     * @memberof ExperimentCollaborators
     */
    readonly role?: string;
}

export function ExperimentCollaboratorsFromJSON(json: any): ExperimentCollaborators {
    return ExperimentCollaboratorsFromJSONTyped(json, false);
}

export function ExperimentCollaboratorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentCollaborators {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : ExperimentUserFromJSON(json['user']),
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function ExperimentCollaboratorsToJSON(value?: ExperimentCollaborators | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': ExperimentUserToJSON(value.user),
    };
}


