/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExperimentTeams,
    ExperimentTeamsFromJSON,
    ExperimentTeamsFromJSONTyped,
    ExperimentTeamsToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserTeam
 */
export interface UserTeam {
    /**
     * 
     * @type {number}
     * @memberof UserTeam
     */
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof UserTeam
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    email?: string;
    /**
     * 
     * @type {Array<ExperimentTeams>}
     * @memberof UserTeam
     */
    readonly groups?: Array<ExperimentTeams>;
}

export function UserTeamFromJSON(json: any): UserTeam {
    return UserTeamFromJSONTyped(json, false);
}

export function UserTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTeam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': json['username'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'groups': !exists(json, 'groups') ? undefined : ((json['groups'] as Array<any>).map(ExperimentTeamsFromJSON)),
    };
}

export function UserTeamToJSON(value?: UserTeam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'email': value.email,
    };
}


