/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Experiment
 */
export interface Experiment {
    /**
     * 
     * @type {string}
     * @memberof Experiment
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Experiment
     */
    'date_created': string;
    /**
     * 
     * @type {string}
     * @memberof Experiment
     */
    'description': string;
    /**
     * 
     * @type {boolean}
     * @memberof Experiment
     */
    'is_private'?: boolean;
    /**
     * 
     * @type {Array<ExperimentTeams>}
     * @memberof Experiment
     */
    'teams'?: Array<ExperimentTeams>;
    /**
     * 
     * @type {Array<ExperimentCollaborators>}
     * @memberof Experiment
     */
    'collaborators'?: Array<ExperimentCollaborators>;
}
/**
 * 
 * @export
 * @interface ExperimentCollaborators
 */
export interface ExperimentCollaborators {
    /**
     * 
     * @type {ExperimentUser}
     * @memberof ExperimentCollaborators
     */
    'user'?: ExperimentUser;
    /**
     * 
     * @type {string}
     * @memberof ExperimentCollaborators
     */
    'role'?: string;
}
/**
 * 
 * @export
 * @interface ExperimentFileUpload
 */
export interface ExperimentFileUpload {
    /**
     * 
     * @type {any}
     * @memberof ExperimentFileUpload
     */
    'file': any;
}
/**
 * 
 * @export
 * @interface ExperimentTeams
 */
export interface ExperimentTeams {
    /**
     * 
     * @type {number}
     * @memberof ExperimentTeams
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExperimentTeams
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ExperimentUser
 */
export interface ExperimentUser {
    /**
     * 
     * @type {number}
     * @memberof ExperimentUser
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExperimentUser
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentUser
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentUser
     */
    'email'?: string;
}
/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface UserTeam
 */
export interface UserTeam {
    /**
     * 
     * @type {number}
     * @memberof UserTeam
     */
    'id'?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof UserTeam
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    'email'?: string;
    /**
     * 
     * @type {Array<ExperimentTeams>}
     * @memberof UserTeam
     */
    'groups'?: Array<ExperimentTeams>;
}

/**
 * ApiApi - axios parameter creator
 * @export
 */
export const ApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {string} userId 
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMemberGroup: async (id: string, userId: string, team?: Team, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addMemberGroup', 'id', id)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('addMemberGroup', 'userId', userId)
            const localVarPath = `/api/teams/{id}/members/{user_id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(team, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExperiment: async (name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('createExperiment', 'name', name)
            // verify required parameter 'dateCreated' is not null or undefined
            assertParamExists('createExperiment', 'dateCreated', dateCreated)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('createExperiment', 'description', description)
            const localVarPath = `/api/experiments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (name !== undefined) { 
                localVarFormParams.append('name', name as any);
            }
    
            if (dateCreated !== undefined) { 
                localVarFormParams.append('date_created', dateCreated as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (isPrivate !== undefined) { 
                localVarFormParams.append('is_private', isPrivate as any);
            }
                if (teams) {
                localVarFormParams.append('teams', teams.join(COLLECTION_FORMATS.csv));
            }

                if (collaborators) {
                localVarFormParams.append('collaborators', collaborators.join(COLLECTION_FORMATS.csv));
            }

    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGroup: async (team?: Team, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/teams/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(team, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delMemberGroup: async (id: string, userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('delMemberGroup', 'id', id)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('delMemberGroup', 'userId', userId)
            const localVarPath = `/api/teams/{id}/members/{user_id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        destroyExperiment: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('destroyExperiment', 'id', id)
            const localVarPath = `/api/experiments/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listExperiments: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/experiments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listGroups: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/teams/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        membersGroup: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('membersGroup', 'id', id)
            const localVarPath = `/api/teams/{id}/members/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mineExperiment: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/experiments/mine/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        myteamsExperiment: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/experiments/myteams/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partialUpdateExperiment: async (id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('partialUpdateExperiment', 'id', id)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('partialUpdateExperiment', 'name', name)
            // verify required parameter 'dateCreated' is not null or undefined
            assertParamExists('partialUpdateExperiment', 'dateCreated', dateCreated)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('partialUpdateExperiment', 'description', description)
            const localVarPath = `/api/experiments/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (name !== undefined) { 
                localVarFormParams.append('name', name as any);
            }
    
            if (dateCreated !== undefined) { 
                localVarFormParams.append('date_created', dateCreated as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (isPrivate !== undefined) { 
                localVarFormParams.append('is_private', isPrivate as any);
            }
                if (teams) {
                localVarFormParams.append('teams', teams.join(COLLECTION_FORMATS.csv));
            }

                if (collaborators) {
                localVarFormParams.append('collaborators', collaborators.join(COLLECTION_FORMATS.csv));
            }

    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partialUpdateGroup: async (id: string, team?: Team, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('partialUpdateGroup', 'id', id)
            const localVarPath = `/api/teams/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(team, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicExperiment: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/experiments/public/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveExperiment: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('retrieveExperiment', 'id', id)
            const localVarPath = `/api/experiments/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveGroup: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('retrieveGroup', 'id', id)
            const localVarPath = `/api/teams/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sharedwithmeExperiment: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/experiments/sharedwithme/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateExperiment: async (id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateExperiment', 'id', id)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('updateExperiment', 'name', name)
            // verify required parameter 'dateCreated' is not null or undefined
            assertParamExists('updateExperiment', 'dateCreated', dateCreated)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('updateExperiment', 'description', description)
            const localVarPath = `/api/experiments/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (name !== undefined) { 
                localVarFormParams.append('name', name as any);
            }
    
            if (dateCreated !== undefined) { 
                localVarFormParams.append('date_created', dateCreated as any);
            }
    
            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (isPrivate !== undefined) { 
                localVarFormParams.append('is_private', isPrivate as any);
            }
                if (teams) {
                localVarFormParams.append('teams', teams.join(COLLECTION_FORMATS.csv));
            }

                if (collaborators) {
                localVarFormParams.append('collaborators', collaborators.join(COLLECTION_FORMATS.csv));
            }

    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGroup: async (id: string, team?: Team, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateGroup', 'id', id)
            const localVarPath = `/api/teams/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(team, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileExperiment: async (id: string, file: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('uploadFileExperiment', 'id', id)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadFileExperiment', 'file', file)
            const localVarPath = `/api/experiments/{id}/upload-file/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiApi - functional programming interface
 * @export
 */
export const ApiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiApiAxiosParamCreator(configuration)
    return {
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {string} userId 
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addMemberGroup(id: string, userId: string, team?: Team, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Team>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addMemberGroup(id, userId, team, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createExperiment(name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createExperiment(name, dateCreated, description, isPrivate, teams, collaborators, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createGroup(team?: Team, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Team>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createGroup(team, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delMemberGroup(id: string, userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delMemberGroup(id, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async destroyExperiment(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.destroyExperiment(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listExperiments(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Experiment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listExperiments(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listGroups(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Team>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listGroups(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsers(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserTeam>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async membersGroup(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Team>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.membersGroup(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mineExperiment(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mineExperiment(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async myteamsExperiment(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.myteamsExperiment(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partialUpdateExperiment(id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partialUpdateExperiment(id, name, dateCreated, description, isPrivate, teams, collaborators, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partialUpdateGroup(id: string, team?: Team, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Team>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partialUpdateGroup(id, team, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publicExperiment(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publicExperiment(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveExperiment(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveExperiment(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveGroup(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Team>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveGroup(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sharedwithmeExperiment(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sharedwithmeExperiment(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateExperiment(id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Experiment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateExperiment(id, name, dateCreated, description, isPrivate, teams, collaborators, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateGroup(id: string, team?: Team, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Team>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateGroup(id, team, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileExperiment(id: string, file: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExperimentFileUpload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFileExperiment(id, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ApiApi - factory interface
 * @export
 */
export const ApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiApiFp(configuration)
    return {
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {string} userId 
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMemberGroup(id: string, userId: string, team?: Team, options?: any): AxiosPromise<Team> {
            return localVarFp.addMemberGroup(id, userId, team, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExperiment(name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: any): AxiosPromise<Experiment> {
            return localVarFp.createExperiment(name, dateCreated, description, isPrivate, teams, collaborators, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGroup(team?: Team, options?: any): AxiosPromise<Team> {
            return localVarFp.createGroup(team, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delMemberGroup(id: string, userId: string, options?: any): AxiosPromise<void> {
            return localVarFp.delMemberGroup(id, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        destroyExperiment(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.destroyExperiment(id, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listExperiments(options?: any): AxiosPromise<Array<Experiment>> {
            return localVarFp.listExperiments(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listGroups(options?: any): AxiosPromise<Array<Team>> {
            return localVarFp.listGroups(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers(options?: any): AxiosPromise<Array<UserTeam>> {
            return localVarFp.listUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        membersGroup(id: string, options?: any): AxiosPromise<Team> {
            return localVarFp.membersGroup(id, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mineExperiment(options?: any): AxiosPromise<Experiment> {
            return localVarFp.mineExperiment(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        myteamsExperiment(options?: any): AxiosPromise<Experiment> {
            return localVarFp.myteamsExperiment(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partialUpdateExperiment(id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: any): AxiosPromise<Experiment> {
            return localVarFp.partialUpdateExperiment(id, name, dateCreated, description, isPrivate, teams, collaborators, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partialUpdateGroup(id: string, team?: Team, options?: any): AxiosPromise<Team> {
            return localVarFp.partialUpdateGroup(id, team, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicExperiment(options?: any): AxiosPromise<Experiment> {
            return localVarFp.publicExperiment(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveExperiment(id: string, options?: any): AxiosPromise<Experiment> {
            return localVarFp.retrieveExperiment(id, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveGroup(id: string, options?: any): AxiosPromise<Team> {
            return localVarFp.retrieveGroup(id, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sharedwithmeExperiment(options?: any): AxiosPromise<Experiment> {
            return localVarFp.sharedwithmeExperiment(options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {string} name 
         * @param {string} dateCreated 
         * @param {string} description 
         * @param {boolean} [isPrivate] 
         * @param {Array<ExperimentTeams>} [teams] 
         * @param {Array<ExperimentCollaborators>} [collaborators] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateExperiment(id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: any): AxiosPromise<Experiment> {
            return localVarFp.updateExperiment(id, name, dateCreated, description, isPrivate, teams, collaborators, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
         * @param {string} id A unique integer value identifying this group.
         * @param {Team} [team] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGroup(id: string, team?: Team, options?: any): AxiosPromise<Team> {
            return localVarFp.updateGroup(id, team, options).then((request) => request(axios, basePath));
        },
        /**
         * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
         * @param {string} id A unique integer value identifying this experiment.
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileExperiment(id: string, file: any, options?: any): AxiosPromise<ExperimentFileUpload> {
            return localVarFp.uploadFileExperiment(id, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiApi - object-oriented interface
 * @export
 * @class ApiApi
 * @extends {BaseAPI}
 */
export class ApiApi extends BaseAPI {
    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {string} id A unique integer value identifying this group.
     * @param {string} userId 
     * @param {Team} [team] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public addMemberGroup(id: string, userId: string, team?: Team, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).addMemberGroup(id, userId, team, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {string} name 
     * @param {string} dateCreated 
     * @param {string} description 
     * @param {boolean} [isPrivate] 
     * @param {Array<ExperimentTeams>} [teams] 
     * @param {Array<ExperimentCollaborators>} [collaborators] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public createExperiment(name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).createExperiment(name, dateCreated, description, isPrivate, teams, collaborators, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {Team} [team] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public createGroup(team?: Team, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).createGroup(team, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {string} id A unique integer value identifying this group.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public delMemberGroup(id: string, userId: string, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).delMemberGroup(id, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {string} id A unique integer value identifying this experiment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public destroyExperiment(id: string, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).destroyExperiment(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public listExperiments(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).listExperiments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public listGroups(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).listGroups(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list` actions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public listUsers(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).listUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {string} id A unique integer value identifying this group.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public membersGroup(id: string, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).membersGroup(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public mineExperiment(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).mineExperiment(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public myteamsExperiment(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).myteamsExperiment(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {string} id A unique integer value identifying this experiment.
     * @param {string} name 
     * @param {string} dateCreated 
     * @param {string} description 
     * @param {boolean} [isPrivate] 
     * @param {Array<ExperimentTeams>} [teams] 
     * @param {Array<ExperimentCollaborators>} [collaborators] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public partialUpdateExperiment(id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).partialUpdateExperiment(id, name, dateCreated, description, isPrivate, teams, collaborators, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {string} id A unique integer value identifying this group.
     * @param {Team} [team] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public partialUpdateGroup(id: string, team?: Team, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).partialUpdateGroup(id, team, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public publicExperiment(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).publicExperiment(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {string} id A unique integer value identifying this experiment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public retrieveExperiment(id: string, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).retrieveExperiment(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {string} id A unique integer value identifying this group.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public retrieveGroup(id: string, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).retrieveGroup(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public sharedwithmeExperiment(options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).sharedwithmeExperiment(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {string} id A unique integer value identifying this experiment.
     * @param {string} name 
     * @param {string} dateCreated 
     * @param {string} description 
     * @param {boolean} [isPrivate] 
     * @param {Array<ExperimentTeams>} [teams] 
     * @param {Array<ExperimentCollaborators>} [collaborators] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public updateExperiment(id: string, name: string, dateCreated: string, description: string, isPrivate?: boolean, teams?: Array<ExperimentTeams>, collaborators?: Array<ExperimentCollaborators>, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).updateExperiment(id, name, dateCreated, description, isPrivate, teams, collaborators, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` actions.  Additionally we also provide extra `magic` actions `members`, `members add` and `members delete`.
     * @param {string} id A unique integer value identifying this group.
     * @param {Team} [team] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public updateGroup(id: string, team?: Team, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).updateGroup(id, team, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.
     * @param {string} id A unique integer value identifying this experiment.
     * @param {any} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public uploadFileExperiment(id: string, file: any, options?: AxiosRequestConfig) {
        return ApiApiFp(this.configuration).uploadFileExperiment(id, file, options).then((request) => request(this.axios, this.basePath));
    }
}


