# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-05-19T14:16:24+00:00

from __future__ import annotations

import os
from typing import List, Optional

from django.apps import apps
from django.conf import settings
from django.core.asgi import get_asgi_application
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.security import HTTPBasicCredentials, HTTPBearer
from starlette.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "workspaces.settings")
apps.populate(settings.INSTALLED_APPS)

app = FastAPI(
    contact={"email": "zoran@metacell.us"},
    description="Salk Workspaces",
    license={"name": "UNLICENSED"},
    title="Salk Workspaces",
    version="1.0.0",
    debug=settings.DEBUG,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_HOSTS or ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# init the auth service
from cloudharness_django.services import init_services
init_services()

# start the kafka event listener
import cloudharness_django.services.events

app.mount("/static", StaticFiles(directory=settings.STATIC_ROOT), name="static")
# app.mount("/media", StaticFiles(directory=settings.MEDIA_ROOT), name="media") # For testing purposes we can enable it
app.mount("/", get_asgi_application())
