# Generated by Django 3.2.11 on 2022-03-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='population',
            unique_together={('experiment', 'name')},
        ),
    ]
