# Generated by Django 3.2.11 on 2022-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_population_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='population',
            name='atlas',
            field=models.CharField(choices=[('salk_cord_10um', 'Salk cord 10um'), ('allen_cord_20um', 'Allen cord 20um')], default='salk_cord_10um', max_length=100),
        ),
    ]
