# Generated by Django 3.2.11 on 2022-04-28 13:08

from django.db import migrations

from api.models import Population
from api.services.population_service import split_cells_per_segment


def split_cells(apps, schema_editor):
    for pop in Population.objects.all():
        split_cells_per_segment(pop)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_population_atlas"),
    ]

    operations = [
        migrations.RunPython(split_cells),
    ]
