# Generated by Django 3.2.11 on 2022-04-28 13:08

from django.db import migrations
from api.models import Population


def split_cells(apps, schema_editor):
    for pop in Population.objects.all():
        pop.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_alter_population_atlas'),
    ]

    operations = [
        migrations.RunPython(split_cells),
    ]
