# Generated by Django 3.2.11 on 2022-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20220519_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='status',
            field=models.CharField(
                choices=[('error', 'Error'), ('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished')],
                default='pending', editable=False, max_length=8),
        ),
    ]
