# Generated by Django 3.2.11 on 2022-05-23 12:48

from django.db import migrations, models

from api.models import Population, PopulationStatus


def migrate_population_status_to_ready(apps, schema_editor):
    for pop in Population.objects.all():
        pop.status = PopulationStatus.READY
        pop.save(skip_workflow=True)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_population_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Error'), (0, 'Idle'), (1, 'Running'), (2, 'Ready')], default=0,
                                      editable=False),
        ),
        migrations.RunPython(migrate_population_status_to_ready),
    ]
