# Generated by Django 4.2 on 2023-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_population_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name="population",
            name="cells",
            field=models.FileField(max_length=255, upload_to="populations"),
        ),
    ]
