# Generated by Django 4.2 on 2023-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="file",
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=""),
        ),
    ]
