# Generated by Django 3.2.11 on 2022-05-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_population_atlas"),
    ]

    operations = []
