# Generated by Django 3.2.11 on 2022-05-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20220428_1308"),
    ]

    operations = []
