# Generated by Django 3.2.11 on 2022-04-28 13:08

from django.db import migrations

from api.models import Population, PopulationStatus
from api.services.population_service import split_cells_per_segment


def update_existent_populations(apps, schema_editor):
    for pop in Population.objects.all():
        split_cells_per_segment(pop)
        pop.generate_images()
        pop.status = PopulationStatus.FINISHED
        pop.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_population_status"),
    ]

    operations = [
        migrations.RunPython(update_existent_populations),
    ]