# Generated by Django 3.2.11 on 2022-02-24 11:35
import os
from django.db import migrations


def create_kc_client_and_roles(apps, schema_editor):
    from workspaces.auth import create_client
    if os.environ.get('KUBERNETES_SERVICE_HOST', None):
        # running in K8S so create the KC client and roles
        create_client()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_kc_client_and_roles),
    ]
