# Generated by Django 3.2.11 on 2022-03-09 07:23
import os
from django.db import migrations

def sync_keycloak_users_groups(apps, schema_editor):
    if os.environ.get('KUBERNETES_SERVICE_HOST', None):
        # running in K8S so sync all KC users
        import workspaces.auth
        from kcoidc.services import get_user_service
        get_user_service().sync_kc_users_groups()

class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(sync_keycloak_users_groups),
    ]
